# TODO: Add profiles and move some settings to environment variables
spring:
  task:
    scheduling:
      pool:
        size: 15
  datasource:
    url: jdbc:postgresql://localhost:5432/gym_diary
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
#  sql:
#    init:
#      platform: postgres
  jpa:
    hibernate.ddl-auto: none
    open-in-view: on
    show-sql: true
  liquibase.enabled: false
#  kafka:
#    bootstrap-servers: localhost:9092

server:
  servlet:
    context-path: /api
  port: 8082
logging:
  level:
    org:
      springframework:
        transaction:
          interceptor: trace